import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Testimonials from '../components/Testimonials'
import { motion, useScroll } from "framer-motion"
import Achievments from '@/components/Achievments'
import Education from '@/components/Education'
import ContactUs from '@/components/ContactUs'
import Home from '@/components/Home'
import ContactUs2 from '@/components/ContactUs2'
import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles
// ..
// import { MyComponent } from '@/components/Vanta_cells'
// import { VANTA } from 'vanta'

const inter = Inter({ subsets: ['latin'] })

// AOS.init({
//   offset: 120,
//   delay: 100,
//   duration: 1000
// })
export default function Index() {
  const { scrollYProgress } = useScroll();
  return (
    <>
      <Head>
        <title>Doc Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
      <Education data-aos="fade-in"></Education>
      <Achievments></Achievments>
      <Testimonials />
      <ContactUs2 />
    </>

  )
}
