import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Testimonials from '../components/Testimonials'
import { motion, useScroll } from "framer-motion"
import Achievments from '@/components/Achievments'
import Education from '@/components/Education'
import Home from '@/components/Home'
import ContactUs2 from '@/components/ContactUs2'
import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles
import Navbar from '@/components/Navbar'
import FAQ from '@/components/FAQ'
import Script from 'next/script'
// ..
import AnchorLink from "react-anchor-link-smooth-scroll";
// import { MyComponent } from '@/components/Vanta_cells'
// import { VANTA } from 'vanta'

const inter = Inter({ subsets: ['latin'] })

// AOS.init({
//   offset: 120,
//   delay: 100,
//   duration: 1000
// })
export default function Index() {
  const { scrollYProgress } = useScroll();
  return (
    <div id='start'>
      <Head>
        <div>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300&display=swap" rel="stylesheet" />
        </div>
        <title>Doc Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Navbar ></Navbar>
      <Home></Home>
      <Education data-aos="fade-in"></Education>
      <Achievments></Achievments>
      <Testimonials />
      <FAQ></FAQ>
      <ContactUs2 />

     
    </div>
  )
}
